### ISSUE TITLE
BNT-5: ICRC-7 NFT Implementation

### ISSUE THREAD

**Issue by benjizhai** [dfinity/grant-rfps#29]
## Overview

Status: Assigned
Project Type: Cooperative - Multiple workers can submit work, and the bounty is shared
Time Commitment: Weeks
Experience Level: Intermediate
Size: USD 7'000 in ICP (at time of distribution)

## Description
As part of the ICRC process, we aim to provide production-level implementation code to speed up adoption. This bounty concerns the ICRC-7 NFT standard which is being finalized in the working group.

The applicant is expected to have understood the current draft of ICRC-7 as well as the intentions of the working group and the design trade-offs made, implement according to the specification, and report back to the working group on a bi-weekly basis about any findings during implementation and suggestions on how the standard could be improved. 

Familiarity with the fungible token standards ICRC-1, ICRC-2, and ICRC-3 is a plus.

## Use Cases
NFTs on the IC.

## Acceptance Criteria
- The implementation shall fully implement the ICRC-7 draft proposal.
- The code shall be of production quality, have good documentation and reasonable test coverage.
- The code shall be open sourced with an MIT license.
- The code will be considered 80% complete when the above criteria are met, and 100% complete when it passes the security audit with all problems fixed (the applicant does not bear the cost of the security audit).

## How to apply?
Include links to previous relevant work.
Include a brief overview of how you will complete the task.
Post your application text in this [thread](https://forum.dfinity.org/t/bnt-5-icrc-7-nft-implementation-rust/19414).

## References
[1] ICRC-7 Github. https://github.com/dfinity/ICRC/tree/main/ICRCs/ICRC-7

**Comment by letmejustputthishere** [comment]
is the working group planning on providing a motoko implementation? if not, could we create a bounty for this as well? currently > 90% of the NFT projects on the IC use motoko canisters

**Comment by domwoe** [comment]
@letmejustputthishere The rationale was to start with one implementation to get some feedback from an implementation. But we could start off with a Motoko implementation as well.

**Comment by letmejustputthishere** [comment]
I personally think a Motoko implementation would make more sense for the reasons stated in my previous comment

**Comment by domwoe** [comment]
Assigned to @holykol

**Comment by jedusor1** [comment]
I'd be more than happy to contribute as well, on the RUST side. Who do I reach out to for this?

**Comment by Fe1777** [comment]
It looks like you're referencing a specific GitHub issue or discussion related to the `dfinity/grant-rfps` repository. Specifically, issue #29, which is labeled as "BNT-5: 1CRC-7 NFT Implementation."

Below I will provide an overview of what Dfinity, RFP, and CRC-7 NFT Implementation refer to, along with some guidance on how to get involved or contribute.

### Overview

#### **DFINITY**
DFINITY is an organization behind the development of the Internet Computer, a decentralized computing platform. It aims to enable the creation of secure, scalable, and efficient decentralized applications (dApps).

#### **RFP (Request For Proposals)**
In the context of grant programs like those from DFINITY, an RFP is a formal document that invites developers and researchers to submit proposals to complete specific projects or research in exchange for funding.

#### **CRC-7 NFT Implementation**
The CRC-7 standard refers to a specification for Non-Fungible Tokens (NFTs) on the Internet Computer. NFTs are unique digital assets, and the 1CRC-7 standard is likely a protocol for creating and managing these assets within the DFINITY ecosystem.

### GitHub Issue #29: BNT-5: 1CRC-7 NFT Implementation
Given that issue #29 is open, you might be looking for ways to contribute, understand the scope, or need some guidance on implementing the CRC-7 NFT standard.

#### **Steps to Get Involved or Contribute**

1. **Read the Issue Description**:
   Go to the GitHub issue at [issue #29](https://github.com/dfinity/grant-rfps/issues/29) and read the description and any comments. This will provide you with the specifics of the RFP and what is being requested.

2. **Understand the Requirements**:
   Thoroughly understand the requirements for the CRC-7 NFT implementation. Look for any linked specifications or documentation in the issue description.

3. **Ask Questions**:
   If there are any ambiguities or you need further clarification, add a comment to the issue to ask questions. The maintainers or other contributors can provide guidance.

4. **Research and Plan**:
   - **Technical Specifications**: If not already provided, you may need to look for the spec for CRC-7 NFTs or similar standards.
   - **Relevant Projects**: Check out existing NFT implementations on the Internet Computer or other platforms to get a sense of best practices.

5. **Implementation**:
   Start implementing the CRC-7 NFT standard according to your understanding and the requirements listed in the issue.

   - **Environment Setup**: Make sure to set up your development environment with the required tools and libraries.
   - **Code**: Develop the code to fulfill the RFP. This might involve smart contract development, user interface design, and integration with other parts of the Internet Computer.
   - **Testing**: Thoroughly test your implementation to ensure it meets the defined standard and works as expected.

6. **Create a Pull Request**:
   Once you have completed the implementation, follow the repository's contribution guidelines to create a pull request. Make sure your PR includes:
   - A comprehensive description of the changes.
   - Any relevant documentation or links to external resources.
   - Test cases demonstrating the functionality.

7. **Engage with Reviewers**:
   Actively engage with reviewers who will provide feedback on your implementation. Be prepared to make revisions based on their comments.

#### **Example Resources**

- **Dfinity Documentation**: Check the [DFINITY Developer Docs](https://smartcontracts.org/docs/) for guidance on developing on the Internet Computer.
- **GitHub Repository**: Explore the [DFINITY GitHub repositories](https://github.com/dfinity) for existing projects and standards.

By following these steps, you can effectively contribute to the BNT-5: 1CRC-7 NFT Implementation in the `dfinity/grant-rfps` repository. If you need specific help with the CRC-7 NFT standard or any other aspect, please provide more details!
