### ISSUE TITLE
BNT-7: DFX Dashboard GUI - A native app

### ISSUE THREAD

**Issue by dfx-json** [dfinity/grant-rfps#35]
## Overview

Status: Assigned
Project Type: Traditional - One applicant is selected to work on the task.
Time Commitment: Weeks
Experience Level: Advanced
Size: USD 10'000 in ICP (at time of distribution)

## Description

A cross-platform native application that provides a graphical abstraction of key `dfx` capabilities.  

For example, the ability to call canisters with arguments is typically done through the command line using `dfx` - this process requires forming method arguments into a string, including escaping double quotes and ensuring brackets are properly closed. This is error-prone and cumbersome. Instead, a DFX Dashboard GUI would provide such a capability by exposing a form in the UI that would allow a user to compose canister arguments and call a canister with the click of a button.

In addition, a DFX Dashboard would provide better interoperability between the local `dfx` identity, and Internet Identity, helping us move towards our goal of a more seamless transition between the two. 

## Use Cases

- editing of dfx.json schema
- calling canisters with arguments; providing the ability to compose canister arguments through a form-based UI
- making dfx identity portable through an integration with Internet Identity
- provide better discoverability of dfx commands / capabilities
- improve  user experience by replacing the terminal for a number of use cases where using the terminal is awkward.

## Requirements

- ability to log-in with, and interoperate with Internet Identity
- ability to compose canister arguments through the UI; call canisters with arguments
- ability to edit JSON configurations used by `dfx` (e.g. `dfx.json`, `networks.json`, `ic-assets.json`)

## Acceptance Criteria

- Open Source license  ([Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0.txt))
- Running on Mac OSX, Linux and Windows

## Remarks

- This could be a starting point for a DFINITY Developer Grant to further improve the developer experience.

## How to apply?

Include links to previous relevant work.
Include a brief overview of how you will complete the task.
Post your application text in [this thread](https://forum.dfinity.org/t/bnt-7-dfx-dashboard-gui-a-native-app/20748).

Please be aware that [Terms and Conditions](https://support.dfinity.org/hc/en-us/articles/4401932915860-DFINITY-DEVELOPER-GRANT-PROGRAMS-TERMS-AND-CONDITIONS) of the DFINITY Developer Grants Program apply.

## References
https://forum.dfinity.org/t/concept-dfx-dashboard/20398

**Comment by boyin0x** [comment]
Hi @dfx-json, @domwoe If this bounty is still open, I would like to apply for it.
Please check my gitcoin portfolio https://bounties.gitcoin.co/boyin0x/portfolio and specially the last one I made for the iExec team https://github.com/boyin0x/iexec-task-manager
Looking forward to work with you guys.

**Comment by domwoe** [comment]
@boyin0x Hey, the bounty has just been opened. Please apply in the linked forum thread. Thanks a lot!

**Comment by boyin0x** [comment]
Hi @dfx-json, @domwoe, just to add a few more things to my application:
I've been trying some UX/Design ideas for the dashboard on the weekend, please check the [figma](https://www.figma.com/file/tyLYDwIPFOTx2nu68f2tvg/Boyin_DFX_Dashboard?type=design&t=PgjkuIFcbNCwNlsQ-1).

Plan:
1- UX and visuals approved by the dfinity team.
2- Write a Tauri App executing Rust commands.
3- Full documentation and resources in a Github repo.

**Comment by domwoe** [comment]
@boyin0x Thanks a lot! As mentioned in my previous comment, please post to https://forum.dfinity.org/t/bnt-7-dfx-dashboard-gui-a-native-app/20748
