### ISSUE TITLE
BNT-6: Point-of-Sale Payment Dapp

### ISSUE THREAD

**Issue by domwoe** [dfinity/grant-rfps#36]
## Overview

Status: Closed
Project Type: Cooperative/Contest - Multiple workers can submit work, and the bounty is shared
Time Commitment: Days
Experience Level: Beginner/Intermediate
Size: USD 7'500 in ICP (at time of distribution)
Deadline: July 16th 11:59pm UTC

## Description

Digital payments in physical environments, e.g. shops, street markets etc., are getting increasingly common. With this bounty, we want to showcase the power of the Internet Computer to quickly set up a Point-of-Sale payment solution accepting ckBTC by just opening a website, and putting up a static QR code.

The solution should work like this:

1. Usage without any account: The merchant enters an existing ckBTC address, and the (open) application monitors the address and notifies the merchant about a payment. The application also allows viewing the transaction history of the ckBTC address.
2. Usage with an account: The merchant can create an account and can either enter an existing ckBTC address or create a new address tied to this account. The merchant can also set up additional notification channels to get notified about a payment by a text message. In this scenario, a backend canister needs to monitor the ckBTC account and trigger a notification, e.g. via HTTPS outcalls to courier/Twilio [1].

## Requirements

- The application allows setting a ckBTC account to monitor. Whenever the account receives a payment it will play a sound and show a notification. 
- The application allows showing a QR code that encodes the ckBTC account, such that a payer can scan the QR code, e.g. with the [NNS wallet dapp](https://nns.ic0.app/). 
- The application allows setting up an account using Internet Identity or [a related authentication method](https://github.com/dfinity/awesome-internet-computer#wallets-and-authentication) in order to set up a new ckBTC wallet.
- In authenticated mode, the application allows transferring ckBTC to another account.
- In authenticated mode, the application allows setting up payment notifications by SMS/text message.
- The application allows to review past transactions of the associated accounts (You can use the [dashboard API](https://icrc-api.internetcomputer.org/docs#/accounts/list_account_transactions_api_v1_ledgers__ledger_canister_id__accounts__id__transactions_get) to fetch the necessary data.
- Nice to have: The application allows to print out the QR code encoding the ckBTC address.

## Acceptance Criteria

- The dapp must be optimized for mobile/tablets.
- The code must be open source with an MIT license.

## Evaluation Criteria

- Design/UX
- Functionality
- Code quality

## How to participate?

Post your submission under the following [forum thread](https://forum.dfinity.org/t/open-bnt-6-point-of-sale-payment-dapp/20814).
Please be aware that [Terms and Conditions](https://support.dfinity.org/hc/en-us/articles/4401932915860-DFINITY-DEVELOPER-GRANT-PROGRAMS-TERMS-AND-CONDITIONS) of the DFINITY Developer Grants Program apply.

## References

[1]  See the [IC-Mailer project](https://github.com/ArgonStudiosXYZ/ic-emailer).

**Comment by domwoe** [comment]
@agostbiro Thank you for your interest. Note that the state of the Bounty is currently "In Review" which means it is not finalized and will be updated. The bounty is final when it is in state "open" and published to the forum.

**Comment by agostbiro** [comment]
@domwoe ah ok, thanks for clarifying!
