### ISSUE TITLE
RFP-2: Agents - Libraries for secure integration with the IC

### ISSUE THREAD

**Issue by domwoe** [dfinity/grant-rfps#4]
## Overview

An IC (Internet Computer) Agent is responsible for encoding and decoding messages used to communicate with the IC via its HTTPS interface, as well as verifying responses from the IC by checking the signature against the public key of the IC.

DFINITY is maintaining two IC agent implementations which can be seen in a template:
- [agent-rs](https://github.com/dfinity/agent-rs) (Rust)
- [agent-js](https://github.com/dfinity/agent-js) (JavaScript/TypeScript)

In addition, there are currently the following community-driven IC agent implementations with varying completeness:

- [icp-client-cpp](https://github.com/Zondax/icp-client-cpp) (C++)
- [ic4j-agent](https://github.com/ic4j/ic4j-agent) (Java/Kotlin)
- [agent_dart](https://github.com/AstroxNetwork/agent_dart) (Dart/Flutter)
- [ic_dart_tools](https://github.com/levifeldman/ic_tools_dart) (Dart/Flutter)
- [agent-go](https://github.com/aviate-labs/agent-go) (Go)
- [IC-Go](https://github.com/mix-labs/IC-Go) (Go)
- [ic-py](https://github.com/rocklabs-io/ic-py) (Python) 
- [ICP.NET](https://github.com/Gekctek/ICP.NET) (C#/.NET/Unity)
- [agent-unity](https://github.com/ShikuLabs/agent-unity) (partial) C# wrapper of agent-rs))
- [ic_agent](https://github.com/tuminfei/ic_agent) (Ruby)
- [ICPKit](https://github.com/kosta-bity/IcpKit) (Swift)

We are open to supporting work on existing agent implementations if features are missing, and we might support additional implementations for languages/frameworks that already exist if there is a good reason for this. In addition, the following agent implementations are desired:

Currently, there are active projects for all agents that have been requested. If you need another client library, please get in touch.

## Requirements

- Implementation of the [HTTPS interface](https://internetcomputer.org/docs/current/references/ic-interface-spec#http-interface) as defined in the IC Interface Specification. In particular, the following endpoints must be implemented: [`call`](https://internetcomputer.org/docs/current/references/ic-interface-spec#http-call), [`read_state`](https://internetcomputer.org/docs/current/references/ic-interface-spec#http-read-state), [`query`](https://internetcomputer.org/docs/current/references/ic-interface-spec#http-query) and [`status`](https://internetcomputer.org/docs/current/references/ic-interface-spec#api-status).
- Calculation of the [`request id`](https://internetcomputer.org/docs/current/references/ic-interface-spec#request-id) using representation-independent hashing
- [Authentication](https://internetcomputer.org/docs/current/references/ic-interface-spec#authentication): A request may be either anonymous or authenticated via [signatures](https://internetcomputer.org/docs/current/references/ic-interface-spec#signatures). For authenticated requests delegation should be supported.
- [CBOR](https://internetcomputer.org/docs/current/references/ic-interface-spec#api-cbor): Requests and responses are CBOR encoded, hence, an IC agent needs to be able to encode/decode CBOR.
- [Candid](https://github.com/dfinity/candid): The IC uses Candid as the interface description language (IDL). An IC agent needs to be able to encode/decode arguments between candid and the agent's programming language.
- Support of [`Principal`](https://internetcomputer.org/docs/current/references/ic-interface-spec#principal) data type.
- IC [certificate](https://internetcomputer.org/docs/current/references/ic-interface-spec#certification) verification: Responses from the `read_state` API include a certificate that needs to be parsed ([to look up the relevant information from the state tree](https://internetcomputer.org/docs/current/references/ic-interface-spec#lookup)) and [verified](https://github.com/dfinity/agent-rs/blob/f3b605d7aba12c90b9a27cdafd6ffbb66e2dd87a/ic-agent/src/agent/mod.rs#L611).  The public key of the IC must be [hard coded in the software](https://github.com/dfinity/agent-rs/blob/5be4836e70a11c901215e8329247f90414349a4c/ic-agent/src/agent/mod.rs#L56). For verification of responses from a local replica [the public key needs to be fetched first](https://github.com/dfinity/agent-rs/blob/d1166ec966d86a336e6998bcbe13c90f07c3d4e7/icx/src/main.rs#L254).

## Acceptance Criteria

- Unit tests
- E2E tests, e.g. using [IC-Ref](https://github.com/dfinity/ic-hs#ic-ref-test-an-acceptance-test-suite), See example in [agent-rs](https://github.com/dfinity/agent-rs/blob/main/ref-tests/tests/ic-ref.rs).
- Documentation
- PR to Agents section on [internetcomputer.org](https://internetcomputer.org/docs/current/developer-docs/build/agents/)

## References

- [Internet Computer Interface Specification](https://internetcomputer.org/docs/current/references/ic-interface-spec)
- [Candid Reference](https://internetcomputer.org/docs/current/references/candid-ref)

**Comment by icwizardmonke** [comment]
I found the Ruby agent.
I will tell you where it is if you give me collaborator status.

**Comment by domwoe** [comment]
Hey @icwizardmonke,

we are aware of the Ruby agent (https://github.com/dfinity/awesome-internet-computer#ruby). There's no way to collaborate on a GitHub issue.

**Comment by icwizardmonke** [comment]
Okay last time we spoke you didn't know where Ruby agent is

https://cdn.discordapp.com/attachments/1056016593261445122/1126168399911850135/Screenshot_2023-07-05-08-07-45-974.jpg

I saw a Dfinity tweet mention the Ruby Agent but had no link.
I replied asking for link. No response.
I replied again explaining I had searched the discord and asked you
https://cdn.discordapp.com/attachments/1056016593261445122/1126168858600943626/Screenshot_2023-07-05-08-12-26-254.jpg

No response.

On the relevant page, here in repo, there is no link to the Ruby Agent.

I could have simply added it through pull request.
Instead we have wasted time discussing here.

**Comment by icwizardmonke** [comment]
If I am unable to be commit code and gain Contributor status, why would I participate in project?

**Comment by domwoe** [comment]
@icwizardmonke FYI, this repo should be ready to accept external contributions now.

**Comment by gromakovsky** [comment]
> We are open to supporting work on existing agent implementations if features are missing, and we might support additional implementations for languages/frameworks that already exist if there is a good reason for this.

Are you open to supporting work on new agent implementations in programming languages that don't have them? E. g. Haskell.

**Comment by domwoe** [comment]
Hi @gromakovsky,

yes, we are! The main ones we'd be interested in are a swift agent and driving the [C++](https://github.com/Zondax/icp-client-cpp) for multiplatform Unreal Engine Development.
