### ISSUE TITLE
BNT-9: Ordinals Canister

### ISSUE THREAD

**Issue by domwoe** [dfinity/grant-rfps#44]
## Overview

Status: Open
Project Type: Cooperative/Contest - Multiple workers can submit work and the bounty is shared
Time Commitment: Days
Experience Level: Beginner - Intermediate
Size: USD 3'000 in ICP (at time of distribution)
Deadline: -

## Description

The current Bitcoin Canister on the Internet Computer only stores the set of unspent transaction outputs (UTXOs). This is not enough information to find out:

-  which ordinals are inside a given UTXO
-  to what level of rarety they belong
-  if they have an associated inscription

Until we have all this information on the Internet Computer, we want to encourage building a sustainable Open Internet Service that allows fetching this information from third-party indexing services using HTTPS outcalls.

## Requirements

- Given a UTXO return a list of ordinal (ranges)
- Given an ordinal return the rarety and inscription (if available)
- Calls to the canister should require cycles to cover the cycles cost of the canister to make it sustainable (similar to the Bitcoin canister itself, or the Exchange Rate Canister)

## Acceptance Criteria

- Open Internet Service deployed to the Internet Computer
- Proper Readme, see [here](https://github.com/dfinity/grant-rfps/blob/main/repo-checklist.md#blue_book-create-an-informative-readme)
- Video Pitch/Demo (max. 4min)
- Open Source license (MIT or Apache-2.0)

## Evaluation Criteria

- Functionality
- Code quality

## Note
There are many APIs that can provide ordinal information. One current prerequisite of the API is that it has to support an IPv6 connection.

## How to participate?

Post your submission in the following [forum thread](https://forum.dfinity.org/t/open-bnt-9-ordinals-canister/21769).
Please be aware that [Terms and Conditions](https://support.dfinity.org/hc/en-us/articles/4401932915860-DFINITY-DEVELOPER-GRANT-PROGRAMS-TERMS-AND-CONDITIONS) of the DFINITY Developer Grants Program apply.

## References

- [Information about Ordinals](https://docs.ordinals.com/)
- [Bitcoin Integration](https://internetcomputer.org/docs/current/developer-docs/integrations/bitcoin/)
- [HTTPS Outcalls](https://internetcomputer.org/docs/current/developer-docs/integrations/https-outcalls/)
- [Exchange Rate Canister](https://internetcomputer.org/docs/current/developer-docs/integrations/exchange-rate/exchange-rate-canister)

**Comment by 3scava1i3r** [comment]
Is this still open?

**Comment by domwoe** [comment]
@3scava1i3r Please jump into the discussion on the forum: https://forum.dfinity.org/t/open-bnt-9-ordinals-canister/21769
