### ISSUE TITLE
BNT-10: (All along) the IC Watchtower

### ISSUE THREAD

**Issue by domwoe** [dfinity/grant-rfps#45]
## Overview

Status: Open
Project Type: Cooperative/Contest - Multiple workers can submit work and the bounty is shared
Time Commitment: Days - weeks
Experience Level: Intermediate/Advanced
Size: USD 5'000 in ICP (at time of distribution)
Deadline: -

## Description

A payment channel on the lightning network is essentially a 2-of-2 multi-sig contract between parties holding Bitcoin. From the perspective of the blockchain, bitcoin is held cooperatively by the 2 parties while each party maintains a local record of its respective ownership. The 2 parties can cooperate at any time to update their balances as frequently as they see fit without making any on-chain Bitcoin transactions.

As long as both parties sign a closure transaction the channel can be closed in a cooperative manner. However, channels can be closed unilaterally by either party via a commitment transaction. If your node goes offline for an extended period of time, the counterparty may attempt to force close the channel via an outdated commitment transaction. 

An IC Watchtower canister would be a tamperproof, high reliability, high availability solution that will constantly monitor the channel state data and submit a penalty transaction should the counterparty maliciously attempt to close the channel with an old state.

## Requirements

- The canister allows for a lightning channel UTXO to be monitored 
- The canister allows for channel state data to be backed up. 
- The canister stores and updates the latest balance of the parties involved
- The canister is able to read any closure or commitment transaction issued by any of the parties using HTTPS outcalls.
- The canister is able to submit a penalty transaction should the commitment transaction be malicious.

## Acceptance Criteria

- Service deployed to the Internet Computer
- Proper Readme, see [here](https://github.com/dfinity/grant-rfps/blob/main/repo-checklist.md#blue_book-create-an-informative-readme)
- Video Pitch/Demo (max. 4min)
- Open Source license (MIT or Apache-2.0)

## Evaluation Criteria

- Functionality
- Code quality

## How to participate?

Post your submission in the following [forum thread](https://forum.dfinity.org/t/open-bnt-10-all-along-the-ic-watchtower/21770).
Please be aware that [Terms and Conditions](https://support.dfinity.org/hc/en-us/articles/4401932915860-DFINITY-DEVELOPER-GRANT-PROGRAMS-TERMS-AND-CONDITIONS) of the DFINITY Developer Grants Program apply.

## References

- https://forum.dfinity.org/t/integration-with-btc-lightning/1882
- [Info about Lightning watchtowers](https://docs.lightning.engineering/the-lightning-network/payment-channels/watchtowers)
- [Bitcoin Integration](https://internetcomputer.org/docs/current/developer-docs/integrations/bitcoin/)
- [HTTPS Outcalls](https://internetcomputer.org/docs/current/developer-docs/integrations/https-outcalls/)

**Comment by Sylvester-dev** [comment]
I would like to work on it.

**Comment by domwoe** [comment]
Hi @Sylvester-dev,

please follow the discussion in the forum: https://forum.dfinity.org/t/open-bnt-10-all-along-the-ic-watchtower/21770
You might be able to collaborate with an other developer.

**Comment by domwoe** [comment]
Closing because of missing interest. If you see this and still want to work on this, please reach out.

**Comment by 0xJoichiro** [comment]
@domwoe can we discuss this?
