### ISSUE TITLE
BNT-16: ckBTC Landing Page Design

### ISSUE THREAD

**Issue by domwoe** [dfinity/grant-rfps#59]
## Overview

Status: Closed
Project Type: Competition
Time Commitment: Days
Experience Level: Intermediate
Size: USD 1000 in ICP (At time of distribution, will be shared among participants)
Deadline: Bitcoin Halving, April 20th, 2024

## Description

Chain-key Bitcoin (ckBTC) provides non-custodial payments with 1-2 second finality and negligible fees. It is a multi-chain bitcoin twin, created by chain-key cryptography and ICP smart contracts that directly hold raw bitcoin without relying on intermediaries.

## Purpose and Target Audience

With this bounty, we'd like to explore the design of a dedicated ckBTC landing page (independent of internetcomputer.org).
The landing page should be focused mainly on potential users of ckBTC. Developers are only a secondary audience.

- Explain why a user should use ckBTC.
- Create confidence in the security of ckBTC.
- Showcase where and how you can use ckBTC.
- Enable users to connect their ICP wallet and exchange BTC for ICP.

##  Expected Content

- What is ckBTC.
- Some real-time information (e.g. TVL, Volume, Number of transactions).
- Directly exchange BTC for ckBTC.
- A graphical overview of how ckBTC works.
- Ecosystem overview where you can use ckBTC.
- A FAQ section.
- Links to developer resources to integrate/leverage ckBTC.

These are not hard requirements.

## Acceptance Criteria

- Figma design of at least a single landing page that can be used as a blueprint for an implementation.
- Responsive design. Includes at least a desktop and mobile view.

## Future Plans

We might give out a second bounty to the winner to work with us to improve the design further.

## How to apply

Post your submission in the following [forum thread](https://forum.dfinity.org/t/bnt-16-ckbtc-landing-page-design/29577).
Please be aware that [Terms and Conditions](https://support.dfinity.org/hc/en-us/articles/4401932915860-DFINITY-DEVELOPER-GRANT-PROGRAMS-TERMS-AND-CONDITIONS) of the DFINITY Developer Grants Program apply.

## References

- https://internetcomputer.org/ckbtc
- https://dashboard.internetcomputer.org/bitcoin

**Comment by anuragasawa20** [comment]
Hello 
I'm actually interested in this opportunity. I have some doubts please help me for those is this landing should be deployed means created by frontend or you just need the design of this, secondly if this should be deployed on ICP or anywhere possible and last is where we can get this writing content which should be included on landing page

**Comment by domwoe** [comment]
Thank you for your interest in this opportunity @anuragasawa20. 

As mentioned in the acceptance criteria, we are only looking for Figma designs for this bounty. The actual implementation will come at a later stage.

I'd also suggest asking further questions in the linked forum thread.
