### ISSUE TITLE
BROKEN DISCORD LINK in readme

### ISSUE THREAD

**Issue by flipchan** [dfinity/grant-rfps#60]
Hello,
The discord link in the readme.md is broken, can someone update it?

![Screenshot_2024-11-20_18-16-06](https://github.com/user-attachments/assets/f2e6d6c3-b5b0-4b42-9c37-75ba0eabbcfb)

Leads to an invalid discord link:      
![Screenshot_2024-11-20_18-12-39](https://github.com/user-attachments/assets/54c0076f-56f3-4ebf-9bba-243d33c26027)

**Comment by LevisNgigi** [comment]
Hello I could do this. What is the bounty? also can i get assigned?

**Comment by LevisNgigi** [comment]
thank you I could still correct that if needed
